### ISSUE TITLE
still warn me : koa deprecated Support for generators will be removed in v3

### ISSUE THREAD

**Issue by guoyang007** [luzuoquan/koa2-history-api-fallback#2]
Firstly thanks for your plugin, but when I'm using rewrites function like the `connect-history-api-fallback` writes, I still got the warning: 

koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md app.js:34:5

and my code in app.js:33-35 is:

```
from:/\/embed\/spark-ui\/spark\-.*/,
to:function(context){
     return context.parsedUrl.pathname.match(/\/embed\/spark-ui\/spark\-.*\/(.*)/)[1]
}
```

so should I still need to use the `koa-convert` plugin?

**Comment by luzuoquan** [comment]
If use the default rewrites, it will be ok? maybe something wrong with custom rewrites
