### ISSUE TITLE
Doesn't work to disableDotRule

### ISSUE THREAD

**Issue by rightaway** [luzuoquan/koa2-history-api-fallback#3]
I'm trying this to get routes with dots in the path to work, but it isn't doing anything. Does it look correct?

```js
app.use(koaHistoryApiFallback({
	disableDotRule: true,
}))

app.listen(3000)
```

**Comment by luzuoquan** [comment]
Sorry, this version doesn't support 'disableDotRule'.  Could you pull a request support?

**Comment by luzuoquan** [comment]
publish v0.1.0

**Comment by luzuoquan** [comment]
publish v0.1.0
